plugins {
    id("com.android.library")
    id 'org.jetbrains.kotlin.android'
}
apply from: "../../../common.gradle"

android {
    namespace "de.danoeh.antennapod.net.sync.gpoddernet"
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':net:sync:service-interface')
    implementation 'androidx.core:core-ktx:1.13.1'

    annotationProcessor "androidx.annotation:annotation:$annotationVersion"
    implementation "androidx.appcompat:appcompat:$appcompatVersion"

    implementation "com.squareup.okhttp3:okhttp:$okhttpVersion"
    implementation "org.apache.commons:commons-lang3:$commonslangVersion"
    implementation "commons-io:commons-io:$commonsioVersion"
    implementation "io.reactivex.rxjava3:rxandroid:$rxAndroidVersion"
    implementation "io.reactivex.rxjava3:rxjava:$rxJavaVersion"

    testImplementation "junit:junit:$junitVersion"
}
